{
 "title": "Universo Hackintosh",
 "description": "Painel para monitoramento do macOS",
 "tags": [
  "Universo Hackintosh",
  "macOS",
  "Apple"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "macOS",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Painel de monitoramento - Universo Hackintosh",
   "type": "text",
   "description": "Use os links abaixo, com certeza você vai levar o seu Hackintosh ao próximo nível!",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Conteúdo|Link para acesso\n:----|:----\nCanal YouTube|https://universohackintosh.com\nDiscord|https://universohackintosh.com/DISCORD\nOSX-Proxmox|https://osx-proxmox.com\nGitHub|https://github.com/luchina-gabriel\n"
   }
  },
  { "title": "Visão rápida do Hackintosh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Tempo na qual o macOS está ligado",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Total de processos",
   "type": "stat",
   "description": "Quantidade total de processos existentes no macOS, independente do status",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumo do processador",
   "type": "gauge",
   "description": "Percentual de uso do processador para processos de usuário, sistema e ociosidade.",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "% Usuário" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       { "params": [ "% Sistema" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "% Ocioso" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Cores (Núcleos de CPU)",
   "type": "stat",
   "description": "Quantidade de núcleos (cores + threads) identificadas pelo macOS",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       { "params": [ "CPUs" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Processos em execução",
   "type": "stat",
   "description": "Quantidade de processos que estão em execução",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "macOS: Consumo de Processador (CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Consumo de CPU (Total %)",
   "type": "timeseries",
   "description": "Consumo total do processador (somando todos os cores/núcleos e todos os tipos de processamento)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "cpu",
     "query": "SELECT 100 - \"usage_idle\" as \"Consumo total %\" FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$macOS$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "intel-imacpro-gabriel.local" }
     ]
    }
   ]
  },
  {
   "title": "Consumo de CPU (Detalhado %)",
   "type": "timeseries",
   "description": "Consumo total do processador de maneira detalhada, mostrando os três principais tipos (iowait, usuário e sistema)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "cpu",
     "query": "SELECT \"usage_iowait\" AS \"iowait (%)\", \"usage_user\" AS \"user (%)\", \"usage_system\" AS \"system (%)\" FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" = 'intel-imacpro-gabriel.local') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       { "params": [ "iowait (%)" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "user (%)" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       { "params": [ "system (%)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Fila de processos (Load Average)",
   "type": "timeseries",
   "description": "Fila de processos no status de pronto para ser executado no processador",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       { "params": [ "Load Average - 1m" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       { "params": [ "Load Average - 5m" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       { "params": [ "Load Average - 15m" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  { "title": "macOS: Uso de memória ram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Consumo de memória",
   "type": "timeseries",
   "description": "Mostra o consumo de memória com relação à memória total",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "Memória total" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       { "params": [ "Memória disponível" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "Memória usada" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Memória livre (%)",
   "type": "gauge",
   "description": "Quantia (em percentual) de memória livre",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Memória usada (%)",
   "type": "gauge",
   "description": "Quantia (em percentual) de memória usada",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Memória Ativa",
   "type": "gauge",
   "description": "Quantia de memória ativa",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Memória Inativa",
   "type": "gauge",
   "description": "Quantia de memória inativa",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "inactive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "macOS: Atividade de swap/paging - Possível falta de memória",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Atividade de paginação (in/out de páginas)",
   "type": "timeseries",
   "description": "Mostra a quantia de página in (entrada) e out (saída) da área de swap do macOS. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "pages in/s" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "pages out/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Quantia da área de swap usada",
   "type": "gauge",
   "description": "Mostra a quantia da área de swap em utilização, em duas métricas",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Usado" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Percentual usado (%)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  { "title": "macOS: Discos & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Atividade de Leitura e Escrita nos discos (throughput)",
   "type": "timeseries",
   "description": "Mostra a quantia de leitura e escrita que os discos apresentam no sistema",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name - $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reads/s" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "writes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Quantidade de espaço usado dos discos",
   "type": "timeseries",
   "description": "Apresenta a quantia de espaço usado de cada volume/disco do macOS",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "Usado" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentual LIVRE dos discos",
   "type": "timeseries",
   "description": "Apresenta o percentual (%) livre de cada ponto de montagem dos discos existentes e em uso no macOS",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "% Livre" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  { "title": "macOS: Atividade de rede", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Atividade de rede (placa ethernet, wireless, etc)",
   "type": "graph",
   "description": "Mostra atividade de rede (download/upload) de todas as interfaces ativas (cabo, wireless, etc)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Recebidos/s" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Enviados/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  },
  {
   "title": "Conexões Ativas",
   "type": "timeseries",
   "description": "Quantia de conexões ativas (netstat)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "field" },
       { "params": [ "Conexões ativas" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$macOS$/" }
     ]
    }
   ]
  }
 ]
}